run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - stylecheck
    - misspell

linters-settings:
  govet:
    check-shadowing: true