run:
  tests: true
  timeout: 5m

linters:
  disable:
    - gofumpt
    - exportloopref
    - depguard
    - forbidigo
    - tagliatelle

issues:
  exclude-rules:
    - linters:
        - revive
      text: "unexported-return: exported func .+ returns unexported type .+, which can be annoying to use"
